#Account info write the username of all your account
account_username:
  - "a"

#Account info write the password of all your account
account_password:
  - "b"

#If check_dm is set to true the bot will also take a screenshot of the dm
check_dm: True

#If forever_loop is set to true the bot will run forever otherwise it will run once
forever_loop: False